/**
 * v1 seed data, transcribed directly from the roadmap screenshot that
 * kicked off this project (no source workbook was available to import).
 * Edit through the app from here on — re-running `npm run db:seed` resets
 * to this baseline.
 */

export const FOCUS_AREAS = [
  "Core Platform",
  "Data",
  "Platform",
  "Experience",
  "Partnerships",
  "Operations",
];

export const TEAMS = [
  "Growth",
  "Core Services",
  "Customer Experience",
  "Data Products",
  "Developer Experience",
  "Integrations",
  "Mobile",
  "Security",
  "Analytics",
  "Monetization",
  "Customer Operations",
  "AI Platform",
  "Infrastructure",
  "Operations",
];

const YEAR = 2026;

export const INITIATIVES = [
  {
    focusArea: "Core Platform",
    team: "Growth",
    title: "Unified Onboarding",
    summary: "Replace fragmented signup flows with a guided account setup experience.",
    currentState: "Account setup is fragmented across multiple steps and ownership models, creating inconsistent activation experiences.",
    futureState: "A guided, unified onboarding flow personalizes setup, surfaces next-best actions, and tracks activation progress end-to-end.",
    successMetrics: "Increase activation rate and time-to-value; decrease setup abandonment.",
    impactedTeams: ["Sales", "Support"],
    status: "completed",
    year: YEAR,
    startMonth: 7,
    endMonth: 7,
  },
  {
    focusArea: "Data",
    team: "Growth",
    title: "Audience Segmentation",
    summary: "Create reusable audience cohorts from behavioral and account signals.",
    currentState: "Behavioral and account signals are spread across tools, limiting consistent targeting and reuse.",
    futureState: "Reusable, governed audience cohorts are available in-product and to go-to-market teams for precise targeting.",
    successMetrics: "Increase campaign relevance and qualified pipeline.",
    impactedTeams: ["Marketing", "Data Science"],
    status: "in_progress",
    year: YEAR,
    startMonth: 8,
    endMonth: 9,
  },
  {
    focusArea: "Platform",
    team: "Core Services",
    title: "API Reliability Program",
    summary: "Harden critical APIs with error budgets, alerting, and automated failover.",
    currentState: "Critical APIs have uneven observability and recovery patterns, increasing the impact of service incidents.",
    futureState: "Core APIs operate with error budgets, actionable alerts, automated failover, and consistent reliability standards.",
    successMetrics: "Maintain 99.95% availability; decrease incident recovery time.",
    impactedTeams: ["All Product Teams"],
    status: "in_progress",
    year: YEAR,
    startMonth: 8,
    endMonth: 8,
  },
  {
    focusArea: "Experience",
    team: "Customer Experience",
    title: "Self-Service Billing",
    summary: "Let customers manage invoices, payment methods, and plan changes without support tickets.",
    currentState: "Customers rely on support for common billing tasks such as invoices, payment updates, and plan changes.",
    futureState: "Customers self-manage billing through a secure, intuitive workspace with clear audit history and fewer support handoffs.",
    successMetrics: "Increase self-service resolution; decrease billing contacts.",
    impactedTeams: ["Finance", "Support"],
    status: "completed",
    year: YEAR,
    startMonth: 8,
    endMonth: 8,
  },
  {
    focusArea: "Data",
    team: "Data Products",
    title: "Insight Copilot",
    summary: "Deliver a governed natural-language assistant for account and performance questions.",
    currentState: "Account and performance insights require manual analysis across dashboards and data tools.",
    futureState: "A governed copilot answers trusted business questions in natural language with citations, guardrails, and feedback loops.",
    successMetrics: "Increase insight adoption; maintain answer quality and data controls.",
    impactedTeams: ["Analytics", "Customer Success"],
    status: "backlog",
    year: YEAR,
    startMonth: null,
    endMonth: null,
  },
  {
    focusArea: "Platform",
    team: "Developer Experience",
    title: "Release Automation",
    summary: "Standardize CI/CD templates and progressive delivery for product services.",
    currentState: "Delivery pipelines differ by service, with manual release steps and inconsistent rollback practices.",
    futureState: "Teams use standardized CI/CD templates, progressive delivery, and automated rollback across supported services.",
    successMetrics: "Decrease deployment lead time and rollback frequency.",
    impactedTeams: ["Engineering", "QA"],
    status: "backlog",
    year: YEAR,
    startMonth: null,
    endMonth: null,
  },
  {
    focusArea: "Partnerships",
    team: "Integrations",
    title: "Partner Marketplace",
    summary: "Launch a catalog for certified integrations and shared go-to-market packages.",
    currentState: "Partners discover and integrate through scattered documentation and bespoke coordination.",
    futureState: "A curated marketplace makes certified integrations, shared value propositions, and activation paths easy to discover.",
    successMetrics: "Increase partner-sourced pipeline and integration adoption.",
    impactedTeams: ["Partnerships", "Sales"],
    status: "backlog",
    year: YEAR,
    startMonth: null,
    endMonth: null,
  },
  {
    focusArea: "Experience",
    team: "Mobile",
    title: "Mobile Workspace Refresh",
    summary: "Modernize core mobile workflows for fast, reliable account management.",
    currentState: "Key mobile workflows are inconsistent and lag behind the web experience.",
    futureState: "Customers complete core workspace tasks on mobile through fast, reliable, and accessible native experiences.",
    successMetrics: "Increase mobile task completion and weekly active users.",
    impactedTeams: ["Design", "Support"],
    status: "in_progress",
    year: YEAR,
    startMonth: 7,
    endMonth: 8,
  },
  {
    focusArea: "Platform",
    team: "Security",
    title: "Identity & Access Controls",
    summary: "Introduce role templates, access reviews, and audit-ready permissions.",
    currentState: "Access permissions are managed inconsistently, with limited review workflows and audit visibility.",
    futureState: "Role templates, access reviews, and auditable controls enforce least-privilege access at scale.",
    successMetrics: "Increase access governance; decrease privileged-access risk.",
    impactedTeams: ["IT", "Compliance"],
    status: "completed",
    year: YEAR,
    startMonth: 7,
    endMonth: 8,
  },
  {
    focusArea: "Data",
    team: "Analytics",
    title: "Metric Governance Hub",
    summary: "Publish certified metrics, owners, definitions, and freshness indicators.",
    currentState: "Metric definitions and ownership vary across reports, creating conflicting views of performance.",
    futureState: "Certified metrics have clear definitions, owners, freshness signals, and a single discovery experience.",
    successMetrics: "Increase trusted-report usage; decrease metric discrepancies.",
    impactedTeams: ["Finance", "Analytics"],
    status: "in_progress",
    year: YEAR,
    startMonth: 7,
    endMonth: 9,
  },
  {
    focusArea: "Core Platform",
    team: "Monetization",
    title: "Usage-Based Packaging",
    summary: "Add flexible packaging and usage metering for expanding customer segments.",
    currentState: "Packaging and billing options do not flex cleanly with customer usage and expansion patterns.",
    futureState: "Usage-based packaging and metering support transparent value alignment, expansion, and scalable monetization.",
    successMetrics: "Increase expansion revenue and packaging conversion.",
    impactedTeams: ["Finance", "Sales Operations"],
    status: "completed",
    year: YEAR,
    startMonth: 7,
    endMonth: 7,
  },
  {
    focusArea: "Operations",
    team: "Customer Operations",
    title: "Support Triage Automation",
    summary: "Route, classify, and prioritize incoming support requests using intent signals.",
    currentState: "Support tickets are manually classified and routed, slowing response and creating uneven prioritization.",
    futureState: "Intent-aware automation classifies, routes, and prioritizes requests so agents focus on complex customer needs.",
    successMetrics: "Decrease first-response time and manual triage effort.",
    impactedTeams: ["Support", "Customer Success"],
    status: "in_progress",
    year: YEAR,
    startMonth: 7,
    endMonth: 12,
  },
  {
    focusArea: "Platform",
    team: "AI Platform",
    title: "Workflow Agent Framework",
    summary: "Provide safe, reusable orchestration patterns for task-focused product agents.",
    currentState: "Teams build AI workflows with inconsistent orchestration, safety controls, and observability.",
    futureState: "A reusable agent framework provides secure orchestration, evaluation, monitoring, and policy controls.",
    successMetrics: "Increase agent delivery speed; maintain security and observability.",
    impactedTeams: ["Engineering", "Security"],
    status: "in_progress",
    year: YEAR,
    startMonth: 9,
    endMonth: 11,
  },
  {
    focusArea: "Experience",
    team: "Customer Experience",
    title: "Proactive Health Scores",
    summary: "Surface adoption and risk signals with recommended actions for account teams.",
    currentState: "Account teams identify adoption risk through manual review and lagging indicators.",
    futureState: "Proactive health scores surface actionable risk, adoption, and expansion signals with recommended interventions.",
    successMetrics: "Increase retention and expansion signal coverage.",
    impactedTeams: ["Customer Success", "Sales"],
    status: "completed",
    year: YEAR,
    startMonth: 7,
    endMonth: 7,
  },
  {
    focusArea: "Platform",
    team: "Infrastructure",
    title: "Cost Intelligence",
    summary: "Give service owners real-time cloud cost attribution and optimization recommendations.",
    currentState: "Cloud cost attribution is delayed and inconsistent, limiting accountability and optimization.",
    futureState: "Service owners receive near-real-time unit-cost visibility and prioritized optimization recommendations.",
    successMetrics: "Decrease unit cost; increase tagged-spend coverage.",
    impactedTeams: ["Finance", "Engineering"],
    status: "in_progress",
    year: YEAR,
    startMonth: 9,
    endMonth: 12,
  },
  {
    focusArea: "Data",
    team: "Data Products",
    title: "Real-Time Event Foundation",
    summary: "Establish a durable event stream for product analytics and downstream automation.",
    currentState: "Product events are fragmented and can arrive late or inconsistently across downstream consumers.",
    futureState: "A durable real-time event foundation provides complete, governed streams for analytics and automation.",
    successMetrics: "Increase event completeness and data latency performance.",
    impactedTeams: ["Analytics", "Integrations"],
    status: "completed",
    year: YEAR,
    startMonth: 7,
    endMonth: 7,
  },
  {
    focusArea: "Partnerships",
    team: "Integrations",
    title: "Enterprise SSO Expansion",
    summary: "Extend SSO, SCIM, and enterprise admin controls for strategic accounts.",
    currentState: "Enterprise identity requirements are handled case by case, slowing strategic-account readiness.",
    futureState: "Expanded SSO, SCIM, and admin controls meet enterprise readiness with streamlined provisioning and governance.",
    successMetrics: "Increase enterprise readiness and sales-cycle velocity.",
    impactedTeams: ["IT", "Sales Engineering"],
    status: "in_progress",
    year: YEAR,
    startMonth: 9,
    endMonth: 10,
  },
  {
    focusArea: "Operations",
    team: "Operations",
    title: "Knowledge Base Modernization",
    summary: "Consolidate internal playbooks into searchable, owner-managed knowledge spaces.",
    currentState: "Internal knowledge is scattered across documents and maintained inconsistently.",
    futureState: "A searchable, owner-managed knowledge base keeps playbooks current and accelerates resolution.",
    successMetrics: "Decrease time-to-resolution and content maintenance effort.",
    impactedTeams: ["Support", "Enablement"],
    status: "backlog",
    year: YEAR,
    startMonth: null,
    endMonth: null,
  },
];
